torchrun --nproc_per_node=4 --master_port=5999 Trainer.py \
  --model_name_or_path ../prompting/llama2-7b-chat-hf/ \
  --data_path ../data/finetune.json \
  --lora True \
  --bf16 True \
  --output_dir output/ \
  --num_train_epochs 3 \
  --per_device_train_batch_size 8 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 200 \
  --save_total_limit 200 \
  --learning_rate 1e-5 \
  --weight_decay 0. \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --deepspeed DeepSpeed.json \
  --gradient_checkpointing True